### ISSUE TITLE
Type hinting errors (mypy)

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-navigator#633]
```
(venv) x1 ➜  ansible-navigator git:(exec) mypy src/ansible_navigator                                                   
src/ansible_navigator/runner/ansible_inventory.py:9: error: Skipping analyzing "ansible_runner": found module but no type hints or library stubs
src/ansible_navigator/runner/ansible_doc.py:12: error: Skipping analyzing "ansible_runner": found module but no type hints or library stubs
src/ansible_navigator/runner/ansible_config.py:8: error: Skipping analyzing "ansible_runner": found module but no type hints or library stubs
src/ansible_navigator/runner/ansible_config.py:8: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
src/ansible_navigator/runner/command_async.py:10: error: Skipping analyzing "ansible_runner": found module but no type hints or library stubs
src/ansible_navigator/runner/command.py:6: error: Skipping analyzing "ansible_runner": found module but no type hints or library stubs
src/ansible_navigator/actions/run.py:666: error: Argument "seconds" to "human_time" has incompatible type "float"; expected "int"
```

Most likely introduced with #623, missed b/c CI not enforcing
